"""End-to-end Lead Pipeline & Event Spine Integration Test for Phase A.

Verifies:
1. Lead Event Ingestion (lead.created)
2. BusinessBrain event processing (Sales Agent qualification -> quote.generated)
3. Operations Agent dispatch (survey.dispatched)
4. ToolRuntime business.leads retrieval
"""
import json
import os
import sys
import unittest
import uuid
from pathlib import Path

# Add root directory to sys.path
ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from management.business_brain import BusinessBrain
from management.tools.tool_runtime import ToolRuntime


class TestLeadPipelineE2E(unittest.TestCase):
    def setUp(self):
        self.brain = BusinessBrain(str(ROOT_DIR))
        self.tools = ToolRuntime(str(ROOT_DIR))
        self.events_file = Path(self.brain.events_file)
        self.events_file.parent.mkdir(parents=True, exist_ok=True)

    def test_end_to_end_lead_to_quote_and_survey(self):
        lead_id = f"lead_test_{uuid.uuid4().hex[:8]}"
        correlation_id = str(uuid.uuid4())

        # 1. Simulate lead.created event emitted from Backend Event Spine
        lead_created_event = {
            "event_id": str(uuid.uuid4()),
            "event_type": "lead.created",
            "actor": "customer",
            "timestamp": "2026-09-18T03:20:00Z",
            "correlation_id": correlation_id,
            "payload": {
                "lead": {
                    "id": lead_id,
                    "customer_name": "Ramesh Kumar",
                    "phone": "9876543210",
                    "city": "Kanpur",
                    "pincode": "208001",
                    "status": "new",
                    "source": "web_survey_modal"
                },
                "commercial": {
                    "monthly_bill": 5000,
                    "roof_area_sqft": 450,
                    "recommended_kw": 4.0,
                    "subsidy_amount": 78000,
                    "estimated_savings": 4400,
                    "city": "Kanpur"
                }
            }
        }

        # 2. Process event through Business Brain
        result = self.brain.process_event(lead_created_event)

        self.assertTrue(result.get("handled"), "BusinessBrain should handle lead.created")
        self.assertEqual(result.get("lead_id"), lead_id)
        
        # Verify Sales Agent generated a qualified quote
        sales_agent_output = result.get("sales_agent", {})
        self.assertEqual(sales_agent_output.get("status"), "qualified_for_followup")
        quote = sales_agent_output.get("quote", {})
        self.assertEqual(quote.get("lead_id"), lead_id)
        self.assertEqual(quote.get("recommended_kw"), 4.0)
        self.assertEqual(quote.get("subsidy_amount"), 78000)

        # Verify downstream events
        events = result.get("events", [])
        event_types = [e.get("event_type") for e in events]
        self.assertIn("quote.generated", event_types)
        self.assertIn("survey.dispatched", event_types)

        # 3. Verify persistence in events.jsonl
        with open(self.events_file, "r", encoding="utf-8") as f:
            lines = [json.loads(line) for line in f if line.strip()]
        
        saved_quotes = [e for e in lines if e.get("event_type") == "quote.generated" and e.get("correlation_id") == correlation_id]
        saved_surveys = [e for e in lines if e.get("event_type") == "survey.dispatched" and e.get("correlation_id") == correlation_id]
        
        self.assertTrue(len(saved_quotes) >= 1, "quote.generated should be persisted to events.jsonl")
        self.assertTrue(len(saved_surveys) >= 1, "survey.dispatched should be persisted to events.jsonl")

        # 4. Verify ToolRuntime business.leads retrieval
        tool_res = self.tools.execute("business.leads")
        self.assertTrue(tool_res.ok, "business.leads tool should execute successfully")
        leads_list = tool_res.output if isinstance(tool_res.output, list) else []
        self.assertTrue(isinstance(leads_list, list), "business.leads should return a list of leads")

        print("\nFull Lead Pipeline E2E Test PASSED:")
        print(f"  - Lead ID: {lead_id}")
        print(f"  - Quote generated by Sales Agent: {quote.get('quote_id')}")
        print(f"  - Survey dispatched by Operations Agent")
        print(f"  - Verified persistence in {self.events_file}")


if __name__ == "__main__":
    unittest.main()
